# Order Service Configuration
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/atlas_orders
    username: ${POSTGRES_USER:atlas}
    password: ${POSTGRES_PASSWORD:atlas123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# SAGA configuration
atlas:
  saga:
    order-timeout: 300000  # 5 minutes
    retry-attempts: 3
    retry-delay: 1000

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
